# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f2c3de4b340890decc1a76da2b9ae4d08cbf3b504c3adb98909512e09a283bebb0884ad23881cbfc54eb582d5279ad46edf030fd28c9c20c2facdfee3a251fa6

test:
  secret_key_base: 8de1e9968fc3b5cc414c07140205fbb90c18652e8b42466d00f7c7fe2128a6a12b2253107770d7ae0c76c56070a02703389c4780fccc8a5e566d3bbd454cfa41

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
